export const POST_INGRIDIENTS_REQUEST = 'POST_INGRIDIENTS_REQUEST';
export const POST_INGRIDIENTS_SUCCESS = 'POST_INGRIDIENTS_SUCCESS';
export const POST_INGRIDIENTS_FAILED = 'POST_INGRIDIENTS_FAILED';