export const POST_INGRIDIENTS_REQUEST: "POST_INGRIDIENTS_REQUEST" = "POST_INGRIDIENTS_REQUEST";
export const POST_INGRIDIENTS_SUCCESS: "POST_INGRIDIENTS_SUCCESS" = "POST_INGRIDIENTS_SUCCESS";
export const POST_INGRIDIENTS_FAILED: "POST_INGRIDIENTS_FAILED" = "POST_INGRIDIENTS_FAILED";

export const GET_ORDER_REQUEST: "GET_ORDER_REQUEST" = "GET_ORDER_REQUEST";
export const GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS" = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAILED: "GET_ORDER_FAILED" = "GET_ORDER_FAILED";

