export const POST_FORGOT_PASSWORD_REQUEST: "POST_FORGOT_PASSWORD_REQUEST" = "POST_FORGOT_PASSWORD_REQUEST";
export const POST_FORGOT_PASSWORD_FAILED: "POST_FORGOT_PASSWORD_FAILED" = "POST_FORGOT_PASSWORD_FAILED";
export const POST_FORGOT_PASSWORD_SUCCESS: "POST_FORGOT_PASSWORD_SUCCESS" = "POST_FORGOT_PASSWORD_SUCCESS";

export const POST_RESET_PASSWORD_REQUEST: "POST_RESET_PASSWORD_REQUEST" = "POST_RESET_PASSWORD_REQUEST";
export const POST_RESET_PASSWORD_FAILED: "POST_RESET_PASSWORD_FAILED" = "POST_RESET_PASSWORD_FAILED";
export const POST_RESET_PASSWORD_SUCCESS: "POST_RESET_PASSWORD_SUCCESS" = "POST_RESET_PASSWORD_SUCCESS";

