export const POST_AUTH_REQUEST: "POST_AUTH_REQUEST" = "POST_AUTH_REQUEST";
export const POST_AUTH_FAILED: "POST_AUTH_FAILED" = "POST_AUTH_FAILED";
export const POST_AUTH_SUCCESS: "POST_AUTH_SUCCESS" = "POST_AUTH_SUCCESS";

export const POST_REGISTER_REQUEST: "POST_REGISTER_REQUEST" = "POST_REGISTER_REQUEST";
export const POST_REGISTER_FAILED: "POST_REGISTER_FAILED" = "POST_REGISTER_FAILED";
export const POST_REGISTER_SUCCESS: "POST_REGISTER_SUCCESS" = "POST_REGISTER_SUCCESS";

export const PATCH_USER_REQUEST: "PATCH_USER_REQUEST" = "PATCH_USER_REQUEST";
export const PATCH_USER_FAILED: "PATCH_USER_FAILED" = "PATCH_USER_FAILED";
export const PATCH_USER_SUCCESS: "PATCH_USER_SUCCESS" = "PATCH_USER_SUCCESS";

export const GET_USER_REQUEST: "GET_USER_REQUEST" = "GET_USER_REQUEST";
export const GET_USER_FAILED: "GET_USER_FAILED" = "GET_USER_FAILED";
export const GET_USER_SUCCESS: "GET_USER_SUCCESS" = "GET_USER_SUCCESS";

export const POST_RESET_TOKEN_REQUEST: "POST_RESET_TOKEN_REQUEST" = "POST_RESET_TOKEN_REQUEST";
export const POST_RESET_TOKEN_FAILED: "POST_RESET_TOKEN_FAILED" = "POST_RESET_TOKEN_FAILED";
export const POST_RESET_TOKEN_SUCCESS: "POST_RESET_TOKEN_SUCCESS" = "POST_RESET_TOKEN_SUCCESS";